# Generated by Django 3.2.6 on 2021-08-30 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_station', models.IntegerField()),
                ('building_year', models.IntegerField()),
                ('coverage_ratio', models.FloatField()),
                ('floor_ratio', models.FloatField()),
                ('property_type', models.CharField(max_length=150)),
                ('municipality', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('nearest_station', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=10)),
                ('use', models.CharField(max_length=10)),
                ('city_planning', models.CharField(max_length=25)),
                ('municipality_code', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='propery_photo')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
