# Generated by Django 3.2.6 on 2021-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyclass',
            name='can_add_posts',
            field=models.BooleanField(default=False),
        ),
    ]
