# Generated by Django 3.2.6 on 2021-08-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_propertyclass_can_add_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyclass',
            name='can_add_posts',
        ),
        migrations.AddField(
            model_name='propertyclass',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
