# Generated by Django 3.2.6 on 2021-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210830_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyclass',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
