# Generated by Django 3.2.6 on 2021-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_propertyclass_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyclass',
            name='age',
            field=models.IntegerField(),
        ),
    ]
