# Generated by Django 3.2.6 on 2021-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_propertyclass_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyclass',
            name='image',
            field=models.ImageField(default='default_property.jpg', upload_to='propery_photo'),
        ),
    ]
