# Generated by Django 3.2.6 on 2021-09-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_alter_propertyclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyclass',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='city_planning',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='coverage_ratio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='district',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='floor_ratio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='municipality',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='nearest_station',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='structure',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='propertyclass',
            name='use',
            field=models.CharField(max_length=100),
        ),
    ]
